project:
  type: website

website:
  title: "Data-Driven Insights: Engineering Analytics for Innovation"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - icon: github
        href: https://github.com/Azham3033
format:
  html:
    theme: darkly
    css: styles.css



