project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    right:
      - href: about.qmd
        text: Home
      - href: index.qmd
        text: blog
      - icon: github
        href: https://github.com/Azham3033
format:
  html:
    theme: darkly
    css: styles.css



